# Rime dictionary
# encoding: utf-8
# 《中文-注音詞庫》
#『洋蔥』
---
name: bopomo_onion.extended
version: "201904"
sort: by_weight
use_preset_vocabulary: true
#max_phrase_length: 7
#min_phrase_weight: 100
import_tables:
  - terra_pinyin_1
  - phrases.cht
...
######## 測試字（測試是否少掉台灣以外的用字） ########
裏面	li3 mian4
高峯	gao1 feng1
################### 以下可自行添加詞句 #####################
